version: '3.4'

networks:
  base:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: none
    volumes:
      - /Users/tanya/DBs/Collections/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - base
